import '@mantine/core/styles.css';
import React from 'react';
import { MantineProvider, ColorSchemeScript } from '@mantine/core';
import { theme } from '@/theme';
import "./globals.css";
import { Nunito } from "next/font/google"
import {ClerkProvider} from "@clerk/nextjs";
import {Metadata} from "next";
import '@mantine/dates/styles.css';
import ContextProvider from "@/app/providers/ContextProvider";

const nunito = Nunito({
    weight: ["400", "500", "600", "700", "800"],
    subsets: ["latin"]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {

    return (
          <html lang="en">
              <head>
                <ColorSchemeScript />
                <link rel="shortcut icon" href="/vercel.svg" />
                <meta
                    name="viewport"
                    content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
                />
              </head>
              <body>
              <MantineProvider theme={theme}>
                        {children}
              </MantineProvider>
              </body>
        </html>
  );
}
